export const BOOK_TYPE_LOAD_REQUEST = "BOOK_TYPE_LOAD_REQUEST";
export const BOOK_TYPE_LOAD_SUCCESS = "BOOK_TYPE_LOAD_SUCCESS";
export const BOOK_TYPE_LOAD_FAIL = "BOOK_TYPE_LOAD_FAIL";
export const BOOK_TYPE_LOAD_RESET = "BOOK_TYPE_LOAD_RESET";

export const CREATE_BOOK_TYPE_REQUEST = "CREATE_BOOK_TYPE_REQUEST";
export const CREATE_BOOK_TYPE_SUCCESS = "CREATE_BOOK_TYPE_SUCCESS";
export const CREATE_BOOK_TYPE_FAIL = "CREATE_BOOK_TYPE_FAIL";
export const CREATE_BOOK_TYPE_RESET = "CREATE_BOOK_TYPE_RESET";