export const BOOK_LOAD_REQUEST = "BOOK_LOAD_REQUEST";
export const BOOK_LOAD_SUCCESS = "BOOK_LOAD_SUCCESS";
export const BOOK_LOAD_FAIL = "BOOK_LOAD_FAIL";
export const BOOK_LOAD_RESET = "BOOK_LOAD_RESET";

export const BOOK_LOAD_SINGLE_REQUEST = "BOOK_LOAD_SINGLE_REQUEST";
export const BOOK_LOAD_SINGLE_SUCCESS = "BOOK_LOAD_SINGLE_SUCCESS";
export const BOOK_LOAD_SINGLE_FAIL = "BOOK_LOAD_SINGLE_FAIL";
export const BOOK_LOAD_SINGLE_RESET = "BOOK_LOAD_SINGLE_RESET";

export const REGISTER_BOOK_REQUEST = "REGISTER_BOOK_REQUEST";
export const REGISTER_BOOK_SUCCESS = "REGISTER_BOOK_SUCCESS";
export const REGISTER_BOOK_FAIL = "REGISTER_BOOK_FAIL";
export const REGISTER_BOOK_RESET = "REGISTER_BOOK_RESET";